//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyOffice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11, 148, 68")]
        public global::System.Drawing.Color BaseGreen {
            get {
                return ((global::System.Drawing.Color)(this["BaseGreen"]));
            }
            set {
                this["BaseGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 121, 50")]
        public global::System.Drawing.Color DarkGreen {
            get {
                return ((global::System.Drawing.Color)(this["DarkGreen"]));
            }
            set {
                this["DarkGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 92, 37")]
        public global::System.Drawing.Color DarkerGreen {
            get {
                return ((global::System.Drawing.Color)(this["DarkerGreen"]));
            }
            set {
                this["DarkerGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37, 169, 90")]
        public global::System.Drawing.Color LightGreen {
            get {
                return ((global::System.Drawing.Color)(this["LightGreen"]));
            }
            set {
                this["LightGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 183, 116")]
        public global::System.Drawing.Color LighterGreen {
            get {
                return ((global::System.Drawing.Color)(this["LighterGreen"]));
            }
            set {
                this["LighterGreen"] = value;
            }
        }
    }
}
